version: 2

project_name: lathe

builds:
  - skip: true

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: samzong
    name: lathe
  prerelease: auto
  name_template: "{{ .Tag }}"
