package render

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/samzong/lathe/internal/overlay"
	"github.com/samzong/lathe/pkg/runtime"
)

const (
	GeneratedRoot  = "internal/generated"
	ModulesGenFile = "internal/generated/modules_gen.go"
)

type moduleCtx struct {
	Module        string
	RuntimePkg    string
	SchemaVersion int
	Ops           []runtime.CommandSpec
}

// RuntimePkg is the import path downstream-generated modules use to reach
// lathe's runtime. Downstream forks import lathe as a library; they do not
// vendor or copy the runtime package into their own tree.
const RuntimePkg = "github.com/samzong/lathe/pkg/runtime"

// RenderModule emits internal/generated/<name>/<name>_gen.go. overrides is
// keyed by command Use string; each override's non-empty fields are baked into
// the corresponding CommandSpec (Aliases are appended, not replaced). Passing
// a nil map means "no overlay", equivalent to the pre-overlay behavior.
func RenderModule(name string, specs []runtime.CommandSpec, overrides map[string]overlay.Override) error {
	merged := make([]runtime.CommandSpec, len(specs))
	copy(merged, specs)
	for i := range merged {
		o, ok := overrides[merged[i].Use]
		if !ok {
			continue
		}
		if o.Short != "" {
			merged[i].Short = o.Short
		}
		if o.Long != "" {
			merged[i].Long = o.Long
		}
		if o.Example != "" {
			merged[i].Example = o.Example
		}
		if len(o.Aliases) > 0 {
			merged[i].Aliases = append(merged[i].Aliases, o.Aliases...)
		}
	}
	var buf strings.Builder
	ctx := moduleCtx{
		Module:        name,
		RuntimePkg:    RuntimePkg,
		SchemaVersion: runtime.SchemaVersion,
		Ops:           merged,
	}
	if err := moduleTmpl.Execute(&buf, ctx); err != nil {
		return err
	}
	outPath := filepath.Join(GeneratedRoot, name, name+"_gen.go")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		_ = os.WriteFile(outPath+".unformatted", []byte(buf.String()), 0o644)
		return err
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d commands\n", outPath, len(specs))
	return nil
}

func RenderModulesGen(names []string) error {
	mp, err := modulePath()
	if err != nil {
		return err
	}
	var buf strings.Builder
	if err := modulesTmpl.Execute(&buf, struct {
		Prefix  string
		Modules []string
	}{Prefix: mp + "/internal/generated/", Modules: names}); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		_ = os.WriteFile(ModulesGenFile+".unformatted", []byte(buf.String()), 0o644)
		return err
	}
	if err := os.WriteFile(ModulesGenFile, formatted, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", ModulesGenFile, len(names))
	return nil
}

var moduleTmpl = template.Must(template.New("gen").Parse(`// Code generated by cmd/codegen. DO NOT EDIT.

package {{.Module}}

import (
	"github.com/spf13/cobra"

	"{{.RuntimePkg}}"
)

const generatedSchemaVersion = {{.SchemaVersion}}

func Mount(root *cobra.Command) {
	runtime.AssertSchema(generatedSchemaVersion)
	runtime.Build(root, {{printf "%q" .Module}}, Specs)
}

var Specs = []runtime.CommandSpec{
{{- range $op := .Ops}}
	{
		Group:       {{printf "%q" $op.Group}},
		Use:         {{printf "%q" $op.Use}},
		{{- if $op.Aliases}}
		Aliases:     []string{ {{- range $op.Aliases}}{{printf "%q" .}}, {{end -}} },
		{{- end}}
		Short:       {{printf "%q" $op.Short}},
		{{- if $op.Long}}
		Long:        {{printf "%q" $op.Long}},
		{{- end}}
		{{- if $op.Example}}
		Example:     {{printf "%q" $op.Example}},
		{{- end}}
		{{- if $op.OperationID}}
		OperationID: {{printf "%q" $op.OperationID}},
		{{- end}}
		{{- if $op.Hidden}}
		Hidden:      true,
		{{- end}}
		{{- if $op.Deprecated}}
		Deprecated:  true,
		{{- end}}
		Method:      {{printf "%q" $op.Method}},
		PathTpl:     {{printf "%q" $op.PathTpl}},
		{{- if $op.Params}}
		Params: []runtime.ParamSpec{
			{{- range $op.Params}}
			{Name: {{printf "%q" .Name}}, Flag: {{printf "%q" .Flag}}, In: {{printf "%q" .In}}, GoType: {{printf "%q" .GoType}}, Help: {{printf "%q" .Help}}, Required: {{.Required}}},
			{{- end}}
		},
		{{- end}}
		{{- if $op.RequestBody}}
		RequestBody: &runtime.RequestBody{
			Required: {{$op.RequestBody.Required}},
			{{- if $op.RequestBody.MediaType}}
			MediaType: {{printf "%q" $op.RequestBody.MediaType}},
			{{- end}}
		},
		{{- end}}
		{{- if or $op.Output.ListPath $op.Output.DefaultColumns $op.Output.ResponseMediaType}}
		Output: runtime.OutputHints{
			{{- if $op.Output.ListPath}}ListPath: {{printf "%q" $op.Output.ListPath}},{{end}}
			{{- if $op.Output.DefaultColumns}}DefaultColumns: []string{
				{{- range $op.Output.DefaultColumns}}{{printf "%q" .}},{{end}}
			},{{end}}
			{{- if $op.Output.ResponseMediaType}}ResponseMediaType: {{printf "%q" $op.Output.ResponseMediaType}},{{end}}
		},
		{{- end}}
	},
{{- end}}
}
`))

var modulesTmpl = template.Must(template.New("modules").Parse(`// Code generated by cmd/codegen. DO NOT EDIT.

package generated

import (
	"github.com/spf13/cobra"

{{- range .Modules}}
	{{.}} "{{$.Prefix}}{{.}}"
{{- end}}
)

// MountModules mounts every module declared in sources.yaml under root.
// The import list above is the single source of truth for which modules
// are compiled into this binary. main.go wires this call after
// app.NewApp() so the framework package never imports downstream code.
func MountModules(root *cobra.Command) {
{{- range .Modules}}
	{{.}}.Mount(root)
{{- end}}
}
`))

// modulePath reads the `module` directive from go.mod in the current working
// directory. Codegen uses this to compute the downstream's own generated/
// package import prefix so a downstream fork can rename its Go module without
// touching codegen source. The runtime package is always imported from lathe
// itself (see RuntimePkg).
func modulePath() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("no module directive in go.mod")
}
