package render

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"text/template"

	"github.com/samzong/lathe/internal/runtime"
)

const (
	GeneratedRoot  = "internal/generated"
	ModulesGenFile = "internal/generated/modules_gen.go"
)

type moduleCtx struct {
	Module     string
	RuntimePkg string
	Ops        []runtime.CommandSpec
}

func RenderModule(name string, specs []runtime.CommandSpec) error {
	mp, err := modulePath()
	if err != nil {
		return err
	}
	var buf strings.Builder
	ctx := moduleCtx{
		Module:     name,
		RuntimePkg: mp + "/internal/runtime",
		Ops:        specs,
	}
	if err := moduleTmpl.Execute(&buf, ctx); err != nil {
		return err
	}
	outPath := filepath.Join(GeneratedRoot, name, name+"_gen.go")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		_ = os.WriteFile(outPath+".unformatted", []byte(buf.String()), 0o644)
		return err
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d commands\n", outPath, len(specs))
	return nil
}

func RenderModulesGen(names []string) error {
	mp, err := modulePath()
	if err != nil {
		return err
	}
	var buf strings.Builder
	if err := modulesTmpl.Execute(&buf, struct {
		Prefix  string
		Modules []string
	}{Prefix: mp + "/internal/generated/", Modules: names}); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		_ = os.WriteFile(ModulesGenFile+".unformatted", []byte(buf.String()), 0o644)
		return err
	}
	if err := os.WriteFile(ModulesGenFile, formatted, 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", ModulesGenFile, len(names))
	return nil
}

var moduleTmpl = template.Must(template.New("gen").Parse(`// Code generated by cmd/codegen. DO NOT EDIT.

package {{.Module}}

import (
	"github.com/spf13/cobra"

	"{{.RuntimePkg}}"
)

// Mount mounts the {{.Module}} command tree under root.
func Mount(root *cobra.Command) {
	runtime.Build(root, {{printf "%q" .Module}}, Specs)
}

// Specs declares every {{.Module}} command as data. The generic runner in
// internal/runtime/build.go consumes this slice at startup.
var Specs = []runtime.CommandSpec{
{{- range $op := .Ops}}
	{
		Group:   {{printf "%q" $op.Group}},
		Use:     {{printf "%q" $op.Use}},
		Short:   {{printf "%q" $op.Short}},
		Method:  {{printf "%q" $op.Method}},
		PathTpl: {{printf "%q" $op.PathTpl}},
		{{- if $op.Params}}
		Params: []runtime.ParamSpec{
			{{- range $op.Params}}
			{Name: {{printf "%q" .Name}}, Flag: {{printf "%q" .Flag}}, In: {{printf "%q" .In}}, GoType: {{printf "%q" .GoType}}, Help: {{printf "%q" .Help}}, Required: {{.Required}}},
			{{- end}}
		},
		{{- end}}
		{{- if $op.HasBody}}
		HasBody: true,
		{{- if $op.BodyRequired}}
		BodyRequired: true,
		{{- end}}
		{{- end}}
		{{- if or $op.Output.ListPath $op.Output.DefaultColumns}}
		Output: runtime.OutputHints{
			{{- if $op.Output.ListPath}}ListPath: {{printf "%q" $op.Output.ListPath}},{{end}}
			{{- if $op.Output.DefaultColumns}}DefaultColumns: []string{
				{{- range $op.Output.DefaultColumns}}{{printf "%q" .}},{{end}}
			},{{end}}
		},
		{{- end}}
	},
{{- end}}
}
`))

var modulesTmpl = template.Must(template.New("modules").Parse(`// Code generated by cmd/codegen. DO NOT EDIT.

package generated

import (
	"github.com/spf13/cobra"

{{- range .Modules}}
	{{.}} "{{$.Prefix}}{{.}}"
{{- end}}
)

// MountModules mounts every module declared in sources.yaml under root.
// The import list above is the single source of truth for which modules
// are compiled into this binary. main.go wires this call after
// app.NewApp() so the framework package never imports downstream code.
func MountModules(root *cobra.Command) {
{{- range .Modules}}
	{{.}}.Mount(root)
{{- end}}
}
`))

var (
	cachedModulePath string
	modulePathErr    error
	modulePathOnce   sync.Once
)

// modulePath reads the `module` directive from go.mod in the current working
// directory and caches the result for the remainder of the process. Codegen
// uses this to compute the generated package's import prefix and the runtime
// package's path, so a downstream fork can rename the Go module without
// touching codegen source.
func modulePath() (string, error) {
	modulePathOnce.Do(func() {
		data, err := os.ReadFile("go.mod")
		if err != nil {
			modulePathErr = fmt.Errorf("read go.mod: %w", err)
			return
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "module ") {
				cachedModulePath = strings.TrimSpace(strings.TrimPrefix(line, "module "))
				return
			}
		}
		modulePathErr = fmt.Errorf("no module directive in go.mod")
	})
	return cachedModulePath, modulePathErr
}
