package render

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/samzong/lathe/internal/sourceconfig"
	"github.com/samzong/lathe/internal/specsync"
	"github.com/samzong/lathe/pkg/config"
	"github.com/samzong/lathe/pkg/runtime"
)

type SkillModule struct {
	Source *sourceconfig.Source
	State  *specsync.State
	Specs  []runtime.CommandSpec
}

type moduleRef struct {
	Module SkillModule
	File   string
}

const skillOwnerFile = ".lathe-codegen-skill"

func RenderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule) error {
	clean := filepath.Clean(root)
	if root == "" || clean == "." || clean == string(filepath.Separator) {
		return fmt.Errorf("invalid skill output directory %q", root)
	}
	if err := verifySkillDirectoryOwned(clean); err != nil {
		return err
	}
	refs := moduleReferences(modules)
	if err := os.RemoveAll(clean); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(clean, "agents"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(clean, "references", "modules"), 0o755); err != nil {
		return err
	}
	files := map[string]string{
		filepath.Join(clean, "SKILL.md"):                 renderSkillMD(manifest, refs),
		filepath.Join(clean, skillOwnerFile):             "generated by lathe cmd/codegen; safe to remove and regenerate\n",
		filepath.Join(clean, "agents", "openai.yaml"):    renderOpenAIYAML(manifest),
		filepath.Join(clean, "references", "catalog.md"): renderCatalogReference(manifest),
	}
	for _, ref := range refs {
		files[filepath.Join(clean, "references", "modules", ref.File)] = renderModuleReference(manifest, ref.Module)
	}
	for path, body := range files {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", clean, len(refs))
	return nil
}

func verifySkillDirectoryOwned(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill output path %q exists and is not a directory", root)
	}
	if _, err := os.Stat(filepath.Join(root, skillOwnerFile)); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("refusing to remove existing non-lathe skill directory %q", root)
		}
		return err
	}
	return nil
}

func SkillDirName(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '-' || r == '_' || r == ' ' || r == '.':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "cli"
	}
	return out
}

func moduleReferences(modules []SkillModule) []moduleRef {
	mods := append([]SkillModule(nil), modules...)
	sort.SliceStable(mods, func(i, j int) bool {
		return moduleName(mods[i]) < moduleName(mods[j])
	})
	used := map[string]int{}
	refs := make([]moduleRef, 0, len(mods))
	for _, mod := range mods {
		base := SkillDirName(moduleName(mod))
		used[base]++
		fileBase := base
		if used[base] > 1 {
			fileBase = fmt.Sprintf("%s-%d", base, used[base])
		}
		refs = append(refs, moduleRef{Module: mod, File: fileBase + ".md"})
	}
	return refs
}

func renderSkillMD(manifest *config.Manifest, refs []moduleRef) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: >\n  Use when operating the %s generated CLI. Discover commands, inspect parameters,\n  check auth state, and execute API operations safely.\n---\n\n", skill, cli)
	fmt.Fprintf(&b, "# %s CLI\n\n", cli)
	fmt.Fprintf(&b, "Use this skill when a user asks you to operate `%s`, inspect its API commands, or find the right generated command for an API task.\n\n", cli)
	b.WriteString("## Workflow\n\n")
	fmt.Fprintf(&b, "1. Search for candidates with `%s search \"<intent>\" --json`; use `--limit` when needed. Search is only candidate discovery.\n", cli)
	fmt.Fprintf(&b, "2. Inspect the exact command with `%s commands show <path...> --json` before executing an unfamiliar command.\n", cli)
	fmt.Fprintf(&b, "3. If the command detail has `auth.required=true`, run `%s auth status --hostname <host>` before execution. If it is not logged in, stop and ask the user to authenticate.\n", cli)
	fmt.Fprintf(&b, "4. Execute only after flags, body, auth, HTTP path, and output hints are clear from `commands show`.\n\n")
	b.WriteString("## General Commands\n\n")
	fmt.Fprintf(&b, "- `%s commands --json`: full generated command catalog.\n", cli)
	fmt.Fprintf(&b, "- `%s commands --include-hidden --json`: include hidden generated commands.\n", cli)
	fmt.Fprintf(&b, "- `%s commands show <path...> --json`: source of truth for one command.\n", cli)
	fmt.Fprintf(&b, "- `%s commands schema --json`: catalog schema version for parser compatibility.\n", cli)
	fmt.Fprintf(&b, "- `%s search \"<intent>\" --json`: ranked candidate commands.\n\n", cli)
	b.WriteString("## References\n\n")
	b.WriteString("- Read `references/catalog.md` for the command discovery protocol and catalog field meanings.\n")
	for _, ref := range refs {
		fmt.Fprintf(&b, "- Read `references/modules/%s` for the `%s` module command index.\n", ref.File, moduleName(ref.Module))
	}
	b.WriteString("\n## Rules\n\n")
	b.WriteString("- Do not guess flags or request body shape from command names.\n")
	b.WriteString("- Do not execute directly from search results; confirm with `commands show` first.\n")
	b.WriteString("- Prefer `-o json` for machine-readable command output unless the user asks for human-readable output.\n")
	b.WriteString("- Use `--file`, `--set`, or `--set-str` for JSON request bodies according to `commands show` body requirements.\n")
	return b.String()
}

func renderOpenAIYAML(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	return fmt.Sprintf("interface:\n  display_name: %s\n  short_description: %s\n  default_prompt: %s\n",
		yamlString(cli+" CLI"),
		yamlString("Use the "+cli+" generated CLI"),
		yamlString("Use $"+skill+" to find and run the right "+cli+" command."),
	)
}

func renderCatalogReference(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	var b strings.Builder
	b.WriteString("# Catalog Protocol\n\n")
	b.WriteString("Use the runtime catalog as the source of truth. Generated references are a fast index; command execution details come from the CLI itself.\n\n")
	b.WriteString("## Search\n\n")
	fmt.Fprintf(&b, "Run `%s search \"<intent>\" --json` to find candidate commands. Use `--limit` to control result count. Treat search output as candidates only.\n\n", cli)
	b.WriteString("## Full Catalog\n\n")
	fmt.Fprintf(&b, "Run `%s commands --json` to inspect the generated command catalog. Use `--include-hidden` only when hidden commands are relevant.\n\n", cli)
	b.WriteString("Key fields:\n\n")
	b.WriteString("- `path`: command path to pass to `commands show` or execute after the CLI name.\n")
	b.WriteString("- `http`: HTTP method and path template.\n")
	b.WriteString("- `flags`: CLI flags, parameter location, type, required state, defaults, enum values, format, and help.\n")
	b.WriteString("- `body`: request body requirement and media type.\n")
	b.WriteString("- `auth`: whether auth is required and which scopes are declared.\n")
	b.WriteString("- `output`: list path, default columns, response media type, pagination, and streaming hints.\n\n")
	b.WriteString("## Command Detail\n\n")
	fmt.Fprintf(&b, "Run `%s commands show <path...> --json` before executing an unfamiliar command. This is the source of truth for flags, body, auth, HTTP path, and output hints.\n\n", cli)
	b.WriteString("## Schema\n\n")
	fmt.Fprintf(&b, "Run `%s commands schema --json` to read the catalog schema version before parsing catalog JSON with durable tooling.\n\n", cli)
	b.WriteString("## Request Bodies\n\n")
	b.WriteString("- `--file path`: read a JSON body from a file.\n")
	b.WriteString("- `--file -`: read a JSON body from stdin.\n")
	b.WriteString("- `--set key.path=value`: build JSON with type inference for booleans, null, integers, and floats.\n")
	b.WriteString("- `--set-str key.path=value`: build JSON while forcing the value to remain a string.\n\n")
	b.WriteString("## Output\n\n")
	b.WriteString("Use `-o json` for machine-readable command output. Other supported formats are `table`, `yaml`, and `raw`.\n\n")
	b.WriteString("## Auth\n\n")
	fmt.Fprintf(&b, "If command detail returns `auth.required=true`, run `%s auth status --hostname <host>` before execution. If no matching host is logged in, stop and ask the user to authenticate.\n", cli)
	return b.String()
}

func renderModuleReference(manifest *config.Manifest, mod SkillModule) string {
	cli := manifest.CLI.Name
	specs := visibleSpecs(mod.Specs)
	var b strings.Builder
	fmt.Fprintf(&b, "# Module `%s`\n\n", moduleName(mod))
	b.WriteString("## Source\n\n")
	if mod.Source != nil {
		fmt.Fprintf(&b, "- Backend: `%s`\n", mod.Source.Backend)
		fmt.Fprintf(&b, "- Repository: %s\n", valueOrUnknown(mod.Source.RepoURL))
		fmt.Fprintf(&b, "- Pinned tag: `%s`\n", valueOrUnknown(mod.Source.PinnedTag))
		for _, line := range sourceInputs(mod.Source) {
			fmt.Fprintf(&b, "- %s\n", line)
		}
	}
	if mod.State != nil && mod.State.ResolvedSHA != "" {
		fmt.Fprintf(&b, "- Resolved SHA: `%s`\n", mod.State.ResolvedSHA)
	}
	b.WriteString("\n")
	if len(specs) == 0 {
		b.WriteString("No visible generated commands. Use `commands --include-hidden --json` if hidden commands are relevant.\n")
		return b.String()
	}
	groups := groupSpecs(specs)
	for _, group := range sortedKeys(groups) {
		fmt.Fprintf(&b, "## %s\n\n", group)
		for _, spec := range groups[group] {
			path := commandPath(cli, moduleName(mod), spec)
			fmt.Fprintf(&b, "### `%s`\n\n", strings.Join(path, " "))
			if spec.Short != "" {
				fmt.Fprintf(&b, "- Summary: %s\n", oneLine(spec.Short))
			}
			fmt.Fprintf(&b, "- HTTP: `%s %s`\n", spec.Method, spec.PathTpl)
			fmt.Fprintf(&b, "- Auth: %s\n", authSummary(spec.Security))
			fmt.Fprintf(&b, "- Body: %s\n", bodySummary(spec.RequestBody))
			if len(spec.Params) == 0 {
				b.WriteString("- Flags: none\n")
			} else {
				b.WriteString("- Flags:\n")
				for _, p := range spec.Params {
					req := ""
					if p.Required {
						req = ", required"
					}
					def := ""
					if p.Default != "" {
						def = fmt.Sprintf(", default `%s`", p.Default)
					}
					format := ""
					if p.Format != "" {
						format = ", " + p.Format
					}
					enum := ""
					if len(p.Enum) > 0 {
						enum = ", one of: " + strings.Join(p.Enum, "|")
					}
					deprecated := ""
					if p.Deprecated {
						deprecated = ", deprecated"
					}
					fmt.Fprintf(&b, "  - `--%s` (%s%s%s%s%s%s): %s\n", p.Flag, p.In, req, def, format, enum, deprecated, oneLine(stripHelpMeta(p.Help)))
				}

			}
			if out := outputSummary(spec.Output); out != "" {
				fmt.Fprintf(&b, "- Output: %s\n", out)
			}
			if spec.Example != "" {
				fmt.Fprintf(&b, "- Example: `%s`\n", strings.ReplaceAll(oneLine(spec.Example), "`", "'"))
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func visibleSpecs(specs []runtime.CommandSpec) []runtime.CommandSpec {
	out := make([]runtime.CommandSpec, 0, len(specs))
	for _, spec := range specs {
		if !spec.Hidden {
			out = append(out, spec)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Group == out[j].Group {
			return out[i].Use < out[j].Use
		}
		return out[i].Group < out[j].Group
	})
	return out
}

func groupSpecs(specs []runtime.CommandSpec) map[string][]runtime.CommandSpec {
	out := map[string][]runtime.CommandSpec{}
	for _, spec := range specs {
		group := spec.Group
		if group == "" {
			group = "Commands"
		}
		out[group] = append(out[group], spec)
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func moduleName(mod SkillModule) string {
	if mod.Source != nil && mod.Source.Name != "" {
		return mod.Source.Name
	}
	if mod.State != nil && mod.State.Source != "" {
		return mod.State.Source
	}
	return "module"
}

func sourceInputs(src *sourceconfig.Source) []string {
	switch src.Backend {
	case sourceconfig.BackendSwagger:
		return []string{"Files: `" + strings.Join(src.Swagger.Files, "`, `") + "`"}
	case sourceconfig.BackendOpenAPI3:
		return []string{"Files: `" + strings.Join(src.OpenAPI3.Files, "`, `") + "`"}
	case sourceconfig.BackendProto:
		lines := []string{"Entries: `" + strings.Join(src.Proto.Entries, "`, `") + "`"}
		if len(src.Proto.ImportRoots) > 0 {
			lines = append(lines, "Import roots: `"+strings.Join(src.Proto.ImportRoots, "`, `")+"`")
		}
		if len(src.Proto.Staging) > 0 {
			lines = append(lines, fmt.Sprintf("Staging entries: `%d`", len(src.Proto.Staging)))
		}
		return lines
	default:
		return nil
	}
}

func commandPath(cli, module string, spec runtime.CommandSpec) []string {
	path := []string{cli, module}
	if spec.Group != "" {
		path = append(path, strings.ToLower(spec.Group))
	}
	return append(path, spec.Use)
}

func authSummary(security *runtime.SecurityHint) string {
	if security != nil && security.Public {
		return "public"
	}
	if security != nil && len(security.Scopes) > 0 {
		return "required; scopes: `" + strings.Join(security.Scopes, "`, `") + "`"
	}
	return "required"
}

func bodySummary(body *runtime.RequestBody) string {
	if body == nil {
		return "none"
	}
	state := "optional"
	if body.Required {
		state = "required"
	}
	if body.MediaType != "" {
		return state + "; media type `" + body.MediaType + "`"
	}
	return state
}

func outputSummary(out runtime.OutputHints) string {
	parts := make([]string, 0, 5)
	if out.ListPath != "" {
		parts = append(parts, "list path `"+out.ListPath+"`")
	}
	if len(out.DefaultColumns) > 0 {
		parts = append(parts, "columns `"+strings.Join(out.DefaultColumns, "`, `")+"`")
	}
	if out.ResponseMediaType != "" {
		parts = append(parts, "response media `"+out.ResponseMediaType+"`")
	}
	if out.Pagination != nil {
		parts = append(parts, "pagination `"+out.Pagination.Strategy+"`")
	}
	if out.Streaming != nil {
		parts = append(parts, "streaming `"+out.Streaming.Strategy+"`")
	}
	return strings.Join(parts, "; ")
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// stripHelpMeta removes the trailing " (...)" annotation that helpText() appends,
// so callers that render the metadata separately don't produce duplicates.
func stripHelpMeta(s string) string {
	if i := strings.LastIndex(s, " ("); i >= 0 && strings.HasSuffix(s, ")") {
		return s[:i]
	}
	return s
}

func valueOrUnknown(s string) string {
	if s == "" {
		return "`unknown`"
	}
	return s
}

func yamlString(s string) string {
	raw, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(raw)
}
